### ISSUE TITLE
Doesn't work on NGNIX.

### ISSUE THREAD

**Issue by mfreak28** [jasontate/raspberry-pi-now-playing#3]
Not sure why but every time I try this on my pi server, it just comes up as a 404.

**Comment by mwllgr** [comment]
Using it on nginx, works perfectly. For support, I'd advise you to at least post your configuration.

**Comment by mfreak28** [comment]
> Using it on nginx, works perfectly. For support, I'd advise you to at least post your configuration.

lmao yeah i had no idea what i was doing. mb
